import { Chat, Message, User } from '../store/useStore';

export function generateMockChats(userAddress: string): Chat[] {
  return [
    {
      id: 'chat_aliterra_announcements',
      type: 'channel',
      name: 'Aliterra Announcements',
      description: 'Official channel for Aliterra Web3 Messenger',
      unreadCount: 3,
      pinned: true,
      lastMessage: {
        id: 'msg_001',
        chatId: 'chat_aliterra_announcements',
        senderId: 'aliterra',
        senderAddress: '0x0000000000000000000000000000000000000001',
        senderName: 'Aliterra',
        content: '🚀 Web3 Messenger v2.0 is now live! New features: encrypted DMs, token gating, NFT avatars.',
        timestamp: Date.now() - 1000 * 60 * 5,
        status: 'delivered',
        type: 'text',
      },
    },
    {
      id: 'chat_web3_general',
      type: 'group',
      name: 'Web3 Builders 🔥',
      description: 'Community of Web3 developers and enthusiasts',
      unreadCount: 12,
      members: ['0xabc...def', '0x123...456', '0x789...abc', userAddress],
      lastMessage: {
        id: 'msg_002',
        chatId: 'chat_web3_general',
        senderId: '0xabc123',
        senderAddress: '0xabc1234567890',
        senderName: 'vitalik.eth',
        content: 'Anyone tried the new L2 bridging solution? Gas fees are insane low 🙌',
        timestamp: Date.now() - 1000 * 60 * 12,
        status: 'delivered',
        type: 'text',
      },
    },
    {
      id: 'chat_defi_alpha',
      type: 'group',
      name: 'DeFi Alpha 💎',
      description: 'Exclusive alpha for DeFi traders',
      unreadCount: 5,
      members: ['0xabc...def', userAddress],
      lastMessage: {
        id: 'msg_003',
        chatId: 'chat_defi_alpha',
        senderId: '0xdef456',
        senderAddress: '0xdef4567890abc',
        senderName: 'defi_whale',
        content: 'New yield farming opportunity just dropped on Arbitrum 👀',
        timestamp: Date.now() - 1000 * 60 * 30,
        status: 'delivered',
        type: 'text',
      },
    },
    {
      id: 'chat_pm_alice',
      type: 'private',
      name: 'alice.eth',
      address: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
      isOnline: true,
      unreadCount: 0,
      lastMessage: {
        id: 'msg_004',
        chatId: 'chat_pm_alice',
        senderId: userAddress,
        senderAddress: userAddress,
        senderName: 'You',
        content: 'Hey! Did you see the new NFT drop?',
        timestamp: Date.now() - 1000 * 60 * 60,
        status: 'read',
        type: 'text',
      },
    },
    {
      id: 'chat_pm_bob',
      type: 'private',
      name: 'bob.crypto',
      address: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
      isOnline: false,
      lastSeen: Date.now() - 1000 * 60 * 45,
      unreadCount: 1,
      lastMessage: {
        id: 'msg_005',
        chatId: 'chat_pm_bob',
        senderId: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderAddress: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderName: 'bob.crypto',
        content: 'Sure, let\'s sync up tomorrow about the DAO proposal',
        timestamp: Date.now() - 1000 * 60 * 120,
        status: 'delivered',
        type: 'text',
      },
    },
    {
      id: 'chat_nft_collectors',
      type: 'group',
      name: 'NFT Collectors 🎨',
      description: 'Share and discuss NFT projects',
      unreadCount: 0,
      members: ['0xabc...def', '0x123...456', userAddress],
      lastMessage: {
        id: 'msg_006',
        chatId: 'chat_nft_collectors',
        senderId: '0xabc123',
        senderAddress: '0xabc1234567890',
        senderName: 'nft_guru',
        content: '📸 Just minted a rare 1/1 from the new collection',
        timestamp: Date.now() - 1000 * 60 * 180,
        status: 'delivered',
        type: 'text',
      },
    },
    {
      id: 'chat_pm_charlie',
      type: 'private',
      name: 'charlie.dao',
      address: '0x9d1a5EC82b6dB3e1BdB5de43fC79FbDc77cc98a',
      isOnline: true,
      unreadCount: 0,
      lastMessage: {
        id: 'msg_007',
        chatId: 'chat_pm_charlie',
        senderId: '0x9d1a5EC82b6dB3e1BdB5de43fC79FbDc77cc98a',
        senderAddress: '0x9d1a5EC82b6dB3e1BdB5de43fC79FbDc77cc98a',
        senderName: 'charlie.dao',
        content: 'Vote on the treasury proposal ends in 2h! 🗳️',
        timestamp: Date.now() - 1000 * 60 * 240,
        status: 'delivered',
        type: 'text',
      },
    },
  ];
}

export function generateMockMessages(chatId: string, userAddress: string): Message[] {
  const now = Date.now();

  const chatMessages: Record<string, Message[]> = {
    chat_aliterra_announcements: [
      {
        id: 'am1',
        chatId,
        senderId: 'aliterra',
        senderAddress: '0x0000000000000000000000000000000000000001',
        senderName: 'Aliterra',
        content: '👋 Welcome to Aliterra Web3 Messenger! The first truly decentralized messaging app built on blockchain.',
        timestamp: now - 1000 * 60 * 60 * 24,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'am2',
        chatId,
        senderId: 'aliterra',
        senderAddress: '0x0000000000000000000000000000000000000001',
        senderName: 'Aliterra',
        content: '🔒 All messages are end-to-end encrypted using your wallet private key. Nobody can read your messages — not even us.',
        timestamp: now - 1000 * 60 * 60 * 12,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'am3',
        chatId,
        senderId: 'aliterra',
        senderAddress: '0x0000000000000000000000000000000000000001',
        senderName: 'Aliterra',
        content: '⚡ New features in v2.0:\n• Token-gated groups\n• NFT profile pictures\n• On-chain message verification\n• Multi-wallet support',
        timestamp: now - 1000 * 60 * 30,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'am4',
        chatId,
        senderId: 'aliterra',
        senderAddress: '0x0000000000000000000000000000000000000001',
        senderName: 'Aliterra',
        content: '🚀 Web3 Messenger v2.0 is now live! New features: encrypted DMs, token gating, NFT avatars.',
        timestamp: now - 1000 * 60 * 5,
        status: 'delivered',
        type: 'text',
      },
    ],
    chat_web3_general: [
      {
        id: 'wg1',
        chatId,
        senderId: '0xabc123',
        senderAddress: '0xabc1234567890',
        senderName: 'vitalik.eth',
        content: 'Good morning frens! 🌅 Market looking green today',
        timestamp: now - 1000 * 60 * 60 * 3,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'wg2',
        chatId,
        senderId: '0xdef456',
        senderAddress: '0xdef4567890abc',
        senderName: 'defi_whale',
        content: 'ETH breaking resistance finally 📈',
        timestamp: now - 1000 * 60 * 60 * 2,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'wg3',
        chatId,
        senderId: userAddress,
        senderAddress: userAddress,
        senderName: 'You',
        content: 'Wagmi! 🔥',
        timestamp: now - 1000 * 60 * 90,
        status: 'read',
        type: 'text',
      },
      {
        id: 'wg4',
        chatId,
        senderId: '0xabc123',
        senderAddress: '0xabc1234567890',
        senderName: 'vitalik.eth',
        content: 'Anyone tried the new L2 bridging solution? Gas fees are insane low 🙌',
        timestamp: now - 1000 * 60 * 12,
        status: 'delivered',
        type: 'text',
      },
    ],
    chat_pm_alice: [
      {
        id: 'alice1',
        chatId,
        senderId: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
        senderAddress: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
        senderName: 'alice.eth',
        content: 'Hey! Are you going to the ETH conference next month?',
        timestamp: now - 1000 * 60 * 60 * 5,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'alice2',
        chatId,
        senderId: userAddress,
        senderAddress: userAddress,
        senderName: 'You',
        content: 'Yes definitely! Already got my ticket. Are you coming too?',
        timestamp: now - 1000 * 60 * 60 * 4,
        status: 'read',
        type: 'text',
      },
      {
        id: 'alice3',
        chatId,
        senderId: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
        senderAddress: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
        senderName: 'alice.eth',
        content: 'Of course! We should meet up there. I\'ll be presenting on ZK proofs 🎤',
        timestamp: now - 1000 * 60 * 60 * 3,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'alice4',
        chatId,
        senderId: userAddress,
        senderAddress: userAddress,
        senderName: 'You',
        content: 'Amazing! That\'s going to be a great talk. ZK is the future 💪',
        timestamp: now - 1000 * 60 * 90,
        status: 'read',
        type: 'text',
      },
      {
        id: 'alice5',
        chatId,
        senderId: userAddress,
        senderAddress: userAddress,
        senderName: 'You',
        content: 'Hey! Did you see the new NFT drop?',
        timestamp: now - 1000 * 60 * 60,
        status: 'read',
        type: 'text',
      },
    ],
    chat_pm_bob: [
      {
        id: 'bob1',
        chatId,
        senderId: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderAddress: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderName: 'bob.crypto',
        content: 'Yo! Have you seen the new governance proposal for the DAO?',
        timestamp: now - 1000 * 60 * 60 * 6,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'bob2',
        chatId,
        senderId: userAddress,
        senderAddress: userAddress,
        senderName: 'You',
        content: 'Yeah I read it. What do you think about the treasury allocation?',
        timestamp: now - 1000 * 60 * 60 * 5,
        status: 'read',
        type: 'text',
      },
      {
        id: 'bob3',
        chatId,
        senderId: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderAddress: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderName: 'bob.crypto',
        content: 'I think we need more for development and less for marketing tbh',
        timestamp: now - 1000 * 60 * 60 * 4,
        status: 'delivered',
        type: 'text',
      },
      {
        id: 'bob4',
        chatId,
        senderId: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderAddress: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
        senderName: 'bob.crypto',
        content: 'Sure, let\'s sync up tomorrow about the DAO proposal',
        timestamp: now - 1000 * 60 * 120,
        status: 'delivered',
        type: 'text',
      },
    ],
  };

  return chatMessages[chatId] || [
    {
      id: `default_1_${chatId}`,
      chatId,
      senderId: 'system',
      senderAddress: '0x0',
      senderName: 'System',
      content: 'This conversation is end-to-end encrypted via your wallet signature.',
      timestamp: now - 1000 * 60 * 60,
      status: 'delivered',
      type: 'system',
    },
  ];
}

export function generateMockContacts(): User[] {
  return [
    {
      address: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
      name: 'alice.eth',
      isOnline: true,
      bio: 'ZK researcher & DeFi enthusiast',
    },
    {
      address: '0x2546BcD3c84621e976D8185a91A922aE77ECEc30',
      name: 'bob.crypto',
      isOnline: false,
      lastSeen: Date.now() - 1000 * 60 * 45,
      bio: 'Building the future of finance 🚀',
    },
    {
      address: '0x9d1a5EC82b6dB3e1BdB5de43fC79FbDc77cc98a',
      name: 'charlie.dao',
      isOnline: true,
      bio: 'DAO governance & tokenomics',
    },
    {
      address: '0xabc1234567890abc1234567890abc12345678901',
      name: 'vitalik.eth',
      isOnline: false,
      lastSeen: Date.now() - 1000 * 60 * 180,
      bio: 'Co-founder of Ethereum',
    },
    {
      address: '0xdef4567890abcdef4567890abcdef4567890abcd',
      name: 'defi_whale',
      isOnline: true,
      bio: 'Professional yield farmer 🌾',
    },
    {
      address: '0x9876543210fedcba9876543210fedcba98765432',
      name: 'nft_guru',
      isOnline: false,
      lastSeen: Date.now() - 1000 * 60 * 30,
      bio: 'NFT curator & artist 🎨',
    },
  ];
}
